### ISSUE TITLE
unhelpful breadcrumb

### ISSUE THREAD

**Issue by chris48s** [DemocracyClub/WhoCanIVoteFor#429] opened 2019-07-18 14:35 UTC
If I hit a candidate profile from `/elections/<ballot_id>`, breadcrumbs try and use the ballot id as a postcode:

![Screenshot at 2019-07-18 15-27-11](https://user-images.githubusercontent.com/6025893/61466264-83d9d300-a971-11e9-9698-c373b6ab1d23.png)

**Comment by chris48s** [comment] 2019-11-28 16:03
Related:

> the "candidates in <constituency>" breadcrumb links to the wrong place if you haven't got to this page by postcode search https://whocanivotefor.co.uk/person/2519/emily-thornberry

**Comment by symroe** [comment] 2019-11-28 17:31
Last comment fixed in 9a856ee4ccbb2523f01c43cd10da2146e27d19c3

As for the initial report – this is expected – it will link to the latest ballot in the breadcrumbs if there's no postcode.

**Comment by chris48s** [comment] 2019-11-28 18:02
> As for the initial report – this is expected – it will link to the latest ballot in the breadcrumbs if there's no postcode

I agree that's the intended behaviour, but that's not what it actually does though:

![GIFrecord_2019-11-28_180058](https://user-images.githubusercontent.com/6025893/69826001-2dc34900-1209-11ea-882c-87cd704728c7.gif)

**Comment by symroe** [comment] 2019-11-28 18:06
Er, huh.

I can't reproduce that…

![beany](https://user-images.githubusercontent.com/242329/69826130-b8a44380-1209-11ea-9bdf-6c70466760cd.gif)

**Comment by chris48s** [comment] 2019-11-28 18:13
So note the original bug report: this happens in the case where we've ended up on the ballot page from `/elections/<ballot_id>` rather than the case where we've followed a deep link to the candidate. Maybe I shouldn't have referenced both variations in one issue.

If you hit https://whocanivotefor.co.uk/person/20/captain-beany with a clean session, it doesn't happen (that's the case in your screen capture), but if you hit https://whocanivotefor.co.uk/elections/parl.aberavon.2019-12-12/ and follow the link to Captain Beany you get the behviour in mine (sorry - should have made that clearer the second time). I think because we've overloaded `/elections` so that it can take a ballot id or a postcode we just always assume the param was as a postcode in that situation rather than working out whether its the `/elections/<ballot_id>` version of the route or the `/elections/<postcode>` version of the route?

**Closed** 2019-11-28 18:41 UTC

**Comment by symroe** [comment] 2019-11-28 18:43
Ok, bit of a hack pushed that does fix this.

Note that the only way to reproduce this was if you typed the URL _without_ the (optional) ballot slug. 

e.g. hitting `https://whocanivotefor.co.uk/elections/parl.aberavon.2019-12-12/` would cause the bug (on the later clicked person page) but `https://whocanivotefor.co.uk/elections/parl.aberavon.2019-12-12/aberavon/` wouldn't.

This explains why I couldn't reproduce it at all – there's no way to find this bug by clicking links on the site, only entering the URL.

Either way, I've been less optimistic about what we consider to be a postcode now.

**Comment by chris48s** [comment] 2019-11-29 17:07
Yeah its an edge case, although we do generally omit the optional slug when we link from another site where we've just got a ballot id (I might have initially hit this following the links on EE).

The workaround will do the job, but we can do something more elegant here. Its not really the thing for either of us to be spend a lot of time on now, so I'll open another issue to remind myself to care about making a slightly better job of this at some point in future. :+1:
